package com.diabeticcare.app.ui.reports

import android.content.Context
import androidx.lifecycle.*
import com.diabeticcare.app.data.repository.GlucoseRepository
import com.diabeticcare.app.data.repository.MealRepository
import com.diabeticcare.app.data.repository.MedicationRepository
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class ReportsViewModel(
    private val glucoseRepo: GlucoseRepository,
    private val medicationRepo: MedicationRepository,
    private val mealRepo: MealRepository
) : ViewModel() {

    private val _adherence7d = MutableLiveData(0)
    val adherence7d: LiveData<Int> = _adherence7d

    private val _adherence30d = MutableLiveData(0)
    val adherence30d: LiveData<Int> = _adherence30d

    private val _isExporting = MutableLiveData(false)
    val isExporting: LiveData<Boolean> = _isExporting

    private val _exportedFile = MutableLiveData<Pair<File, String>?>()
    val exportedFile: LiveData<Pair<File, String>?> = _exportedFile

    private var reportDays = 7

    fun setReportDays(days: Int) { reportDays = days }

    fun loadAdherence() {
        viewModelScope.launch {
            _adherence7d.postValue(medicationRepo.adherenceScoreLast(7))
            _adherence30d.postValue(medicationRepo.adherenceScoreLast(30))
        }
    }

    fun generatePdfReport(context: Context, days: Int) {
        viewModelScope.launch {
            _isExporting.postValue(true)
            try {
                val readings = glucoseRepo.snapshotLast(days)
                val meals = mealRepo.snapshotLast(days)
                val sdf = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
                val file = File(context.getExternalFilesDir(null),
                    "Glydecare_Report_${SimpleDateFormat("yyyyMMdd", Locale.getDefault()).format(Date())}.txt")

                file.writeText(buildString {
                    appendLine("╔══════════════════════════════════════╗")
                    appendLine("║       Glydecare Health Report        ║")
                    appendLine("╚══════════════════════════════════════╝")
                    appendLine("Generated: ${sdf.format(Date())}")
                    appendLine("Period: Last $days days")
                    appendLine()
                    appendLine("── GLUCOSE READINGS (${readings.size} total) ──")
                    readings.forEach { r ->
                        appendLine("${sdf.format(Date(r.timestamp))}  |  ${r.value} mg/dL  |  ${r.readingType}")
                    }
                    val avg = if (readings.isNotEmpty()) readings.map { it.value }.average() else 0.0
                    appendLine()
                    appendLine("Average: ${"%.1f".format(avg)} mg/dL")
                    appendLine()
                    appendLine("── MEALS LOGGED (${meals.size} total) ──")
                    meals.forEach { m ->
                        appendLine("${sdf.format(Date(m.timestamp))}  |  ${m.mealType}  |  ${m.portionSize}  |  ${m.foodCategory}")
                    }
                    appendLine()
                    appendLine("── MEDICATION ADHERENCE ──")
                    appendLine("${days}-day adherence: ${medicationRepo.adherenceScoreLast(days)}%")
                    appendLine()
                    appendLine("-- Generated by Glydecare --")
                    appendLine("Dr G Hari Prakash, Ramaiah University of Applied Sciences")
                })
                _exportedFile.postValue(Pair(file, "text/plain"))
            } catch (e: Exception) {
                _exportedFile.postValue(null)
            } finally {
                _isExporting.postValue(false)
            }
        }
    }

    fun exportCsv(context: Context, days: Int) {
        viewModelScope.launch {
            _isExporting.postValue(true)
            try {
                val readings = glucoseRepo.snapshotLast(days)
                val file = File(context.getExternalFilesDir(null),
                    "Glydecare_Glucose_${SimpleDateFormat("yyyyMMdd", Locale.getDefault()).format(Date())}.csv")
                val sdf = SimpleDateFormat("dd-MM-yyyy,HH:mm", Locale.getDefault())
                FileWriter(file).use { w ->
                    w.appendLine("Date,Time,Glucose_mgdL,Type,Notes")
                    readings.forEach { r ->
                        val dt = sdf.format(Date(r.timestamp)).split(",")
                        w.appendLine("${dt[0]},${dt[1]},${r.value},${r.readingType},${r.notes.replace(",", ";")}")
                    }
                }
                _exportedFile.postValue(Pair(file, "text/csv"))
            } catch (e: Exception) {
                _exportedFile.postValue(null)
            } finally {
                _isExporting.postValue(false)
            }
        }
    }
}

class ReportsViewModelFactory(
    private val glucoseRepo: GlucoseRepository,
    private val medicationRepo: MedicationRepository,
    private val mealRepo: MealRepository
) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        @Suppress("UNCHECKED_CAST")
        return ReportsViewModel(glucoseRepo, medicationRepo, mealRepo) as T
    }
}
